I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 102, in script
    show Naomi Happy PlaceHolder
Exception: Image 'Naomi Happy' does not accept attributes 'PlaceHolder'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 102, in script
    show Naomi Happy PlaceHolder
  File "C:\Program Files (x86)\Ren'py\renpy-8.3.4-sdk\renpy\ast.py", line 1117, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Program Files (x86)\Ren'py\renpy-8.3.4-sdk\renpy\ast.py", line 1080, in show_imspec
    renpy.config.show(name,
  File "C:\Program Files (x86)\Ren'py\renpy-8.3.4-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Program Files (x86)\Ren'py\renpy-8.3.4-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Program Files (x86)\Ren'py\renpy-8.3.4-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Program Files (x86)\Ren'py\renpy-8.3.4-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'Naomi Happy' does not accept attributes 'PlaceHolder'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
Xmas Project 1.0
Wed Apr  2 09:53:21 2025
